"""add revenue ranges and plan pricing

Revision ID: 80d711047dbe
Revises: 293878c8358a
Create Date: 2025-07-06 13:38:38.341379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80d711047dbe'
down_revision: Union[str, None] = '293878c8358a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_ranges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_ranges'))
    )
    op.create_table('plan_pricings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('revenue_range_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_pricings_plan_id_plans')),
    sa.ForeignKeyConstraint(['revenue_range_id'], ['revenue_ranges.id'], name=op.f('fk_plan_pricings_revenue_range_id_revenue_ranges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_pricings')),
    sa.UniqueConstraint('plan_id', 'revenue_range_id', name='uq_plan_revenue_range')
    )
    op.drop_column('plans', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00'))
    op.drop_table('plan_pricings')
    op.drop_table('revenue_ranges')
    # ### end Alembic commands ###