"""add annual revenue to customers

Revision ID: e7db710c0f7e
Revises: 80d711047dbe
Create Date: 2025-07-06 13:40:44.585459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7db710c0f7e'
down_revision: Union[str, None] = '80d711047dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'annual_revenue')
    # ### end Alembic commands ###